name: 'Surge Github Action'
description: 'Auto Deploy your project on push with Surge.sh'
inputs:
  domain:
    description: 'the desired domain name'
    default: '_'
  path:
    description: 'the project build output dir'
    default: './dist'

outputs:
  domain:
    description: 'the published domain'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: cloud
  color: 'green'
  